spring:
  application:
    name: reactive-tasks
  r2dbc:
    # Puedes usar URL directa o construirla con DB_HOST/DB_PORT/DB_NAME/DB_SSL_MODE
    url: ${SPRING_R2DBC_URL:r2dbc:pool:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:appdb}?sslMode=${DB_SSL_MODE:disable}}
    username: ${SPRING_R2DBC_USERNAME:${DB_USER:app}}
    password: ${SPRING_R2DBC_PASSWORD:${DB_PASSWORD:secret}}

  sql:
    init:
      mode: always # en prod se desactiva
server:
  port: ${PORT:8080}

management:
  endpoints:
    web:
      exposure:
        include: health,info

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /docs
    operationsSorter: method
